### ISSUE TITLE
Driver 340.102-1 does not work in Fedora 25

### ISSUE THREAD

**Issue by KritonK** [negativo17/nvidia-kmod-340#1]
The new 340.102-1 release of the legacy nVidia driver does not work in Fedora 25, displaying the same behavior as the previous version, before it was patched for Xorg 1.19.

Looking at the source of nvidia-kmod-340.102-1, I don't see the patch, which means that either nVidia did not update the driver for Xorg 1.19, despite their claims to the contrary, or older code is being used in the package.

Applying the patch for 1.19 fixes the problem. For convenience, I remind you that you can download the  patch here:
http://pastebin.com/raw/mSwYvy1L
which I found in this discussion:
https://devtalk.nvidia.com/default/topic/982052/linux/latest-nvidia-driver-340-101-builds-compiles-properly-but-fails-to-load-has-errors-with-linux-kernel-4-9-resolved-with-patch-/

I have not checked the dkms version, to see if the problem is there, as well.

**Comment by jp7677** [comment]
Or in other words, please resurrect https://github.com/negativo17/nvidia-kmod-340/blob/ff4ba3b0c2b4a42c256fdc904c50df17a4d662c0/kernel-4.9.patch.

**Comment by scaronni** [comment]
Applied, new build coming.
I will probably retire this repository soon, I don't have any hardware to test. That's why it's not advertised. I'm maintaining it out of feedback from a couple of friends, but I think it's time to retire it.

I will make a note on the blog and remove it in a few weeks.
